language: python
python:
  - "3.4"
  - "3.5"

# command to install dependencies
install:
  - "pip install flake8"
  - "pip install -r requirements.txt"

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - "cd kboard && flake8 --exit-zero . && cd .."

# command to run tests
script:
 - cd kboard && coverage run --source=board manage.py test board/
 - python manage.py test functional_test/
after_success:
  coveralls
