# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 13:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_auto_20161010_1046'),
        ('board', '0004_summernote'),
    ]

    operations = [
    ]
