# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_auto_20161012_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.TextField(default='', null=True),
        ),
    ]
