# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_auto_20161012_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.TextField(default=''),
        ),
        migrations.AlterUniqueTogether(
            name='post',
            unique_together=set([]),
        ),
        migrations.AlterIndexTogether(
            name='post',
            index_together=set([('title', 'content')]),
        ),
    ]
