# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-24 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0011_auto_20161023_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='page_view_count',
            field=models.IntegerField(default=1),
        ),
    ]
