# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-31 20:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0014_auto_20161101_0512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='user',
        ),
    ]
